apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocolo: 'TCP'
      port: 5000
      targetPort: 5000
  type: loadBalancer

  # executando o servico
  # kubectl apply -f flask-service.yaml
  # kubectl get services
  # minikube service flask-service