# criando uma imagem do Python 2.7
FROM python:2.7

WORKDIR /app

COPY . .

CMD ["python", "app/app.py"]

# criando a imagem no terminal -> docker build -t python27-image
# executar o container no terminal -> docker run -it --rm python27-image
